### ISSUE TITLE
Wrong device detected

### ISSUE THREAD

**Issue by ankushs92** [spring-projects/spring-mobile#31]
Here is my user agent

Mozilla/5.0 (Linux; Android 4.4.2; SAMSUNG-SM-N900A Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36

This is wrongly being identified as a Tablet. There are several other user agents that should be identified to a Mobile Device,but is rather being resolved to a Tablet.

**Comment by royclarkson** [comment]
Thanks for reporting. The problem is that the user-agent does not indicate that the device is a mobile device. We don't keep track of every device, but rather inspect the user-agent for the word `mobile`. Google suggests that [UAs without "mobile" are considered tablets](https://developer.chrome.com/multidevice/user-agent).
